const { chromium } = require('playwright');
const fs = require('fs');
const path = require('path');
const sharp = require('sharp');

/**
 * Captures a screenshot of a web page
 * @param {string} url - URL of the page to capture
 * @param {Object} options - Configuration options
 * @param {string} options.outputPath - Path where to save the screenshot
 * @param {string} options.outputFilename - Screenshot filename
 * @param {boolean} options.fullPage - Capture the entire page or just the visible part
 * @param {boolean} options.generateMarkdown - Generate a Markdown file with the embedded image
 * @param {string} options.markdownTitle - Title of the Markdown file
 * @returns {Promise<Object>} - Information about the screenshot
 */
async function captureScreenshot(url, options = {}) {
  // Default options
  const defaultOptions = {
    outputPath: process.cwd(),
    outputFilename: 'screenshot.png',
    fullPage: true,
    generateMarkdown: true,
    markdownTitle: 'Automatic Screenshot',
    waitForSelector: null,
    waitForTimeout: 1000,
    imageFormat: 'jpg',
    imageQuality: 80
  };

  // Merge default options with provided options
  const config = { ...defaultOptions, ...options };
  
  // Full paths for output files
  let screenshotPath = path.join(config.outputPath, config.outputFilename);
  const jpgPath = screenshotPath.replace(/\.(png|jpg|jpeg)$/i, '.jpg');
  const markdownPath = config.markdownPath || path.join(config.outputPath, 'screenshot_to_share.md');
  
  // Launch the browser
  const browser = await chromium.launch();
  
  try {
    // Create a new browser context
    const context = await browser.newContext();
    
    // Open a new page
    const page = await context.newPage();
    
    // Navigate to the specified URL
    await page.goto(url);
    
    // Wait for the page to be fully loaded
    await page.waitForLoadState('networkidle');
    
    // Wait for a specific selector if requested
    if (config.waitForSelector) {
      await page.waitForSelector(config.waitForSelector);
    }
    
    // Wait for an additional delay if specified
    if (config.waitForTimeout > 0) {
      await page.waitForTimeout(config.waitForTimeout);
    }
    
    // Take a screenshot (initially as PNG)
    await page.screenshot({ 
      path: screenshotPath, 
      fullPage: config.fullPage 
    });
    
    console.log(`Screenshot saved to ${screenshotPath}`);
    
    // Convert and compress the image to JPG
    try {
      // Check if sharp is installed
      if (typeof sharp !== 'function') {
        console.log('Sharp module not found. Using original PNG image.');
      } else {
        await sharp(screenshotPath)
          .jpeg({ quality: config.imageQuality })
          .toFile(jpgPath);
        
        console.log(`Compressed JPG image saved to ${jpgPath}`);
        
        // Use the JPG file for the markdown
        if (fs.existsSync(jpgPath)) {
          screenshotPath = jpgPath;
        }
      }
    } catch (error) {
      console.warn('Error compressing image:', error.message);
      console.log('Using original PNG image.');
    }
    
    // Generate a Markdown file if requested
    let markdownFilePath = null;
    if (config.generateMarkdown) {
      // Convert the image to Base64
      const imageBuffer = fs.readFileSync(screenshotPath);
      const base64Image = imageBuffer.toString('base64');
      const mimeType = screenshotPath.endsWith('.jpg') ? 'image/jpeg' : 'image/png';
      
      // Create a Markdown file with the embedded image
      const markdownContent = `# ${config.markdownTitle}
      
Date: ${new Date().toLocaleString()}

![Screenshot of the web page](data:${mimeType};base64,${base64Image})

*This image was automatically generated by the screenshot tool*
`;
      
      fs.writeFileSync(markdownPath, markdownContent);
      console.log(`Markdown file created with embedded image: ${markdownPath}`);
      markdownFilePath = markdownPath;
    }
    
    return {
      success: true,
      screenshotPath,
      markdownPath: markdownFilePath,
      timestamp: new Date().toISOString()
    };
  } catch (error) {
    console.error('Error while capturing screenshot:', error);
    return {
      success: false,
      error: error.message
    };
  } finally {
    // Close the browser
    await browser.close();
  }
}

module.exports = { captureScreenshot };
